# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 133b47b23ff94bb33d0d8ae590b5d69d1bbf92afb2402873c272859573421a6deac78901f4371258df55d4deb87ee93410a56fed4a345b4938964f32cdabc31e

test:
  secret_key_base: 5d7b4decdfec0879706bacf03690b72f5f748597ca3440249af6c74f45107d123a4cb4c777688dd45483b572ccbcf7c8a05e5c15cacd6a3ca2c033b1ff48a0a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
